language: php

addons:
  apt:
    update: true
    packages:
      - libwebp-dev
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - ./configure --with-gd --with-jpeg-dir=/usr --with-webp-dir=/usr --with-vpx-dir=/usr --with-png-dir=/usr --enable-exif

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
